import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/authProvider";

import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
  title: "Anonymous Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <head />
      <AuthProvider>
        <body>
          <main>{children}</main>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  )
}
